/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AppSettings {
  'websiteName' : string,
  'qrNote' : string,
  'showQrOnBill' : boolean,
  'contact' : string,
  'websiteLogoBase64' : string,
  'billLogoBase64' : string,
  'showTax' : boolean,
  'gstin' : string,
  'address' : string,
  'upiId' : string,
  'shopName' : string,
  'gstinEnabled' : boolean,
}
export interface CartItem {
  'mrp' : number,
  'qty' : bigint,
  'name' : string,
  'imageBase64' : string,
  'menuItemId' : string,
}
export interface MenuItem {
  'id' : string,
  'mrp' : number,
  'name' : string,
  'barcode' : string,
  'imageBase64' : string,
  'barcodeEnabled' : boolean,
}
export interface Order {
  'id' : string,
  'customerName' : string,
  'total' : number,
  'customerPhone' : string,
  'date' : string,
  'orderNo' : bigint,
  'timestamp' : string,
  'discount' : number,
  'paymentMode' : string,
  'items' : Array<CartItem>,
  'cashAmount' : number,
  'subtotal' : number,
}
export interface User {
  'id' : string,
  'username' : string,
  'password' : string,
  'role' : string,
}
export interface _SERVICE {
  'addOrder' : ActorMethod<[Order], undefined>,
  'getMenuItems' : ActorMethod<[], Array<MenuItem>>,
  'getOrderCounter' : ActorMethod<[], bigint>,
  'getOrders' : ActorMethod<[], Array<Order>>,
  'getSettings' : ActorMethod<[], AppSettings>,
  'getUsers' : ActorMethod<[], Array<User>>,
  'incrementOrderCounter' : ActorMethod<[], bigint>,
  'setMenuItems' : ActorMethod<[Array<MenuItem>], undefined>,
  'setOrders' : ActorMethod<[Array<Order>], undefined>,
  'setSettings' : ActorMethod<[AppSettings], undefined>,
  'setUsers' : ActorMethod<[Array<User>], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];