/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CartItem = IDL.Record({
  'mrp' : IDL.Float64,
  'qty' : IDL.Nat,
  'name' : IDL.Text,
  'imageBase64' : IDL.Text,
  'menuItemId' : IDL.Text,
});
export const Order = IDL.Record({
  'id' : IDL.Text,
  'customerName' : IDL.Text,
  'total' : IDL.Float64,
  'customerPhone' : IDL.Text,
  'date' : IDL.Text,
  'orderNo' : IDL.Nat,
  'timestamp' : IDL.Text,
  'discount' : IDL.Float64,
  'paymentMode' : IDL.Text,
  'items' : IDL.Vec(CartItem),
  'cashAmount' : IDL.Float64,
  'subtotal' : IDL.Float64,
});
export const MenuItem = IDL.Record({
  'id' : IDL.Text,
  'mrp' : IDL.Float64,
  'name' : IDL.Text,
  'barcode' : IDL.Text,
  'imageBase64' : IDL.Text,
  'barcodeEnabled' : IDL.Bool,
});
export const AppSettings = IDL.Record({
  'websiteName' : IDL.Text,
  'qrNote' : IDL.Text,
  'showQrOnBill' : IDL.Bool,
  'contact' : IDL.Text,
  'websiteLogoBase64' : IDL.Text,
  'billLogoBase64' : IDL.Text,
  'showTax' : IDL.Bool,
  'gstin' : IDL.Text,
  'address' : IDL.Text,
  'upiId' : IDL.Text,
  'shopName' : IDL.Text,
  'gstinEnabled' : IDL.Bool,
});
export const User = IDL.Record({
  'id' : IDL.Text,
  'username' : IDL.Text,
  'password' : IDL.Text,
  'role' : IDL.Text,
});

export const idlService = IDL.Service({
  'addOrder' : IDL.Func([Order], [], []),
  'getMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
  'getOrderCounter' : IDL.Func([], [IDL.Nat], ['query']),
  'getOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getSettings' : IDL.Func([], [AppSettings], ['query']),
  'getUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
  'incrementOrderCounter' : IDL.Func([], [IDL.Nat], []),
  'setMenuItems' : IDL.Func([IDL.Vec(MenuItem)], [], []),
  'setOrders' : IDL.Func([IDL.Vec(Order)], [], []),
  'setSettings' : IDL.Func([AppSettings], [], []),
  'setUsers' : IDL.Func([IDL.Vec(User)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CartItem = IDL.Record({
    'mrp' : IDL.Float64,
    'qty' : IDL.Nat,
    'name' : IDL.Text,
    'imageBase64' : IDL.Text,
    'menuItemId' : IDL.Text,
  });
  const Order = IDL.Record({
    'id' : IDL.Text,
    'customerName' : IDL.Text,
    'total' : IDL.Float64,
    'customerPhone' : IDL.Text,
    'date' : IDL.Text,
    'orderNo' : IDL.Nat,
    'timestamp' : IDL.Text,
    'discount' : IDL.Float64,
    'paymentMode' : IDL.Text,
    'items' : IDL.Vec(CartItem),
    'cashAmount' : IDL.Float64,
    'subtotal' : IDL.Float64,
  });
  const MenuItem = IDL.Record({
    'id' : IDL.Text,
    'mrp' : IDL.Float64,
    'name' : IDL.Text,
    'barcode' : IDL.Text,
    'imageBase64' : IDL.Text,
    'barcodeEnabled' : IDL.Bool,
  });
  const AppSettings = IDL.Record({
    'websiteName' : IDL.Text,
    'qrNote' : IDL.Text,
    'showQrOnBill' : IDL.Bool,
    'contact' : IDL.Text,
    'websiteLogoBase64' : IDL.Text,
    'billLogoBase64' : IDL.Text,
    'showTax' : IDL.Bool,
    'gstin' : IDL.Text,
    'address' : IDL.Text,
    'upiId' : IDL.Text,
    'shopName' : IDL.Text,
    'gstinEnabled' : IDL.Bool,
  });
  const User = IDL.Record({
    'id' : IDL.Text,
    'username' : IDL.Text,
    'password' : IDL.Text,
    'role' : IDL.Text,
  });
  
  return IDL.Service({
    'addOrder' : IDL.Func([Order], [], []),
    'getMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
    'getOrderCounter' : IDL.Func([], [IDL.Nat], ['query']),
    'getOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getSettings' : IDL.Func([], [AppSettings], ['query']),
    'getUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
    'incrementOrderCounter' : IDL.Func([], [IDL.Nat], []),
    'setMenuItems' : IDL.Func([IDL.Vec(MenuItem)], [], []),
    'setOrders' : IDL.Func([IDL.Vec(Order)], [], []),
    'setSettings' : IDL.Func([AppSettings], [], []),
    'setUsers' : IDL.Func([IDL.Vec(User)], [], []),
  });
};

export const init = ({ IDL }) => { return []; };